export const projects = [
    {
        title: "SDLC AI - Software Delivery Copilot",
        description: "Designed a software delivery assistant that turns requirements, architecture notes, and sprint context into traceable plans, implementation guidance, and review-ready artifacts.",
        tags: ["SDLC AI", "Agentic AI", "RAG", "LangGraph", "NextJS", "FastAPI"],
        slug: "sdlc-ai",
        image: "/sdlc-ai.png",
    },
    {
        title: "Agentic Xtractor - SimplifyAI",
        description: "Built an agentic extraction pipeline for complex engineering PDFs, combining LangGraph planning, Qdrant retrieval, and reviewable structured output.",
        tags: ["LangGraph", "Qdrant", "Python", "FastAPI", "Agentic AI", "SimplifyAI"],
        slug: "agentic-xtractor",
        image: "/xtractor.png",
    },
    {
        title: "BEJO App - Modular RAG System",
        description: "Built a production-ready RAG system with FastAPI, Next.js, and Qdrant. Supports dynamic agent routing and local deployment via Ollama.",
        tags: ["FastAPI", "NextJS", "Qdrant", "Ollama", "LangGraph", "Generative AI"],
        slug: "bejo-app-rag-system",
        image: "/bejo.png",
    },
    {
        title: "Predictive Maintenance System",
        description: "Implemented multivariate time-series classification with LightGBM to predict equipment leaks and failures, paired with a real-time Streamlit dashboard.",
        tags: ["LightGBM", "Time Series", "Machine Learning", "Streamlit", "Python"],
        slug: "predictive-maintenance-system",
        image: "/predictive.png",
    },
    {
        title: "GEMASTIK 2024 - Sentiment Analysis",
        description: "Analyzed Google Play Store reviews with IndoBERT to surface actionable product insights for the Mobile Bea Cukai app.",
        tags: ["IndoBERT", "NLP", "Sentiment Analysis", "Python", "GEMASTIK"],
        slug: "gemastik-2024-sentiment-analysis",
        image: "/ristek.PNG",
    },
    {
        title: "From Fundamentals to Generative AI Excellence",
        description: "Completed the Bangkit Academy Machine Learning path led by Google, Tokopedia, Gojek, and Traveloka, spanning ML foundations through generative AI.",
        tags: ["Machine Learning", "Deep Learning", "NLP", "Generative AI", "Computer Vision", "Tensorflow"],
        slug: "from-fundamentals-to-generative-ai-excellence",
        image: "/bangkit.jfif",
    },
    {
        title: "LLM Utility Suite",
        description: "Built an LLM-powered Next.js application with paper summarization, CV review, cover-letter generation, and practical AI utility flows.",
        tags: ["NextJS", "TailwindCSS", "Firebase", "LLM", "Generative AI", "Gemini", "Groq"],
        slug: "developed-a-nextjs-application-integrating-llm",
        image: "/og-projects.PNG",
    },
    {
        title: "InterSim AI - Personalized Job Interview Coach",
        description: "Developed an adaptive interview simulation tool using BERT similarity analysis and a fine-tuned LLaMA question generator for job-specific practice.",
        tags: ["BERT", "IntesimQS", "LLaMA-3.2", "Huggingface", "FastAPI", "Capstone Project"],
        slug: "intersim-ai",
        image: "/hf.PNG",
    },
    {
        title: "Traffic Congestion Prediction Model",
        description: "Built a London traffic congestion prediction model with XGBoost during Ristek Datathon UI, ranking 43rd out of 88 teams.",
        tags: ["XGBoost", "Traffic Prediction", "Machine Learning", "Python"],
        slug: "traffic-congestion-prediction-model",
        image: "/og-home.PNG",
    },
]
